version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `infrastructure` directory
    directory: "/infrastructure"
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    versioning-strategy: auto
    # Specify labels for npm pull requests
    labels:
      - "dependencies"
    allow:
      - dependency-type: "all"
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `request-echo` directory
    directory: "/lambdas/request-echo"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    versioning-strategy: auto
    labels:
      - "dependencies"
    allow:
      - dependency-type: "all"

  - package-ecosystem: "github-actions"
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: "/"
    schedule:
      interval: "daily"
