# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Test request echo function

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      uses: actions/setup-node@v3.0.0
      with:
        node-version: 14.x
    - run: npm ci
      working-directory: lambdas/request-echo
    - run: npm run test
      working-directory: lambdas/request-echo
